#!/usr/bin/env python3
"""Constraint cost of the Merkle helpers per tree depth (#528).

For every depth from 1 to `MAX_TREE_DEPTH` (read from circuits/lib/src/merkle.nr)
this script compiles two throwaway circuits against the shared library:

  verify  main(leaf, index, path: [Field; D], root: pub Field)
          -> verify_merkle_proof_generic::<D>
  root    main(leaves: [Field; 2^D]) -> pub Field
          -> compute_merkle_root_generic::<2^D, D>   (depths up to --root-max-depth)

and records ACIR opcodes (`nargo info --json`) and, when bb is on PATH, the
UltraHonk gate count (`bb gates`). It then rewrites docs/merkle-depth.md.

Usage:
  python3 scripts/bench_merkle_depth.py                 # regenerate the doc
  python3 scripts/bench_merkle_depth.py --root-max-depth 10
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LIB = ROOT / "circuits" / "lib"
DOC = ROOT / "docs" / "merkle-depth.md"


def run(cmd: list[str], cwd: Path | None = None) -> str:
    proc = subprocess.run(cmd, cwd=cwd, text=True, capture_output=True, check=False)
    if proc.returncode != 0:
        raise RuntimeError(f"{' '.join(cmd)} failed:\n{proc.stderr or proc.stdout}")
    return proc.stdout


def max_tree_depth() -> int:
    src = (LIB / "src" / "merkle.nr").read_text()
    match = re.search(r"pub global MAX_TREE_DEPTH: u32 = (\d+);", src)
    if not match:
        raise RuntimeError("MAX_TREE_DEPTH not found in merkle.nr")
    return int(match.group(1))


def project(workdir: Path, name: str, body: str) -> Path:
    path = workdir / name
    (path / "src").mkdir(parents=True)
    (path / "Nargo.toml").write_text(
        f'[package]\nname = "{name}"\ntype = "bin"\ncompiler_version = ">=0.36.0"\n\n'
        f'[dependencies]\nstellar_poker_lib = {{ path = "{LIB}" }}\n'
    )
    (path / "src" / "main.nr").write_text(body)
    return path


def acir_opcodes(path: Path) -> int:
    info = json.loads(run(["nargo", "info", "--json", "--program-dir", str(path)]))
    for fn in info["programs"][0]["functions"]:
        if fn["name"] == "main":
            return int(fn["opcodes"])
    raise RuntimeError(f"no main in {path}")


def gates(path: Path, name: str) -> int | None:
    if shutil.which("bb") is None:
        return None
    run(["nargo", "compile", "--program-dir", str(path)])
    out = run(["bb", "gates", "--scheme", "ultra_honk", "-b", str(path / "target" / f"{name}.json")])
    return int(json.loads(out)["functions"][0]["circuit_size"])


def measure(depth: int, workdir: Path, with_root: bool) -> dict:
    leaves = 1 << depth
    verify = project(
        workdir,
        f"verify_d{depth}",
        "use stellar_poker_lib::merkle;\n"
        f"fn main(leaf: Field, index: u32, path: [Field; {depth}], root: pub Field) {{\n"
        f"    merkle::verify_merkle_proof_generic::<{depth}>(leaf, index, path, root);\n"
        "}\n",
    )
    row = {
        "depth": depth,
        "leaves": leaves,
        "verify_acir": acir_opcodes(verify),
        "verify_gates": gates(verify, f"verify_d{depth}"),
        "root_acir": None,
        "root_gates": None,
    }
    if with_root:
        root = project(
            workdir,
            f"root_d{depth}",
            "use stellar_poker_lib::merkle;\n"
            f"fn main(leaves: [Field; {leaves}]) -> pub Field {{\n"
            f"    merkle::compute_merkle_root_generic::<{leaves}, {depth}>(leaves)\n"
            "}\n",
        )
        row["root_acir"] = acir_opcodes(root)
        row["root_gates"] = gates(root, f"root_d{depth}")
    return row


def fmt(v) -> str:
    return "n/a" if v is None else f"{v:,}"


IN_USE = {6: "52-card deck (`deal_valid`, `reveal_board_valid`, `showdown_valid`, `muck_valid`)", 7: "104-card double deck",
          9: "multi-deck shoe (`deal_valid_shoe`, `deal_valid_shoe_8d`)", 12: "rank table (`rank_table.nr`)"}


def render(rows: list[dict], max_depth: int, nargo: str, bb: str | None) -> str:
    lines = [
        "# Merkle Depth Parameterization",
        "",
        f"_Generated by `scripts/bench_merkle_depth.py` with Noir `{nargo}`"
        + (f" and bb `{bb}`" if bb else " (bb not available, gate columns empty)")
        + ". Re-run the script to refresh the tables; the prose around them is maintained by hand._",
        "",
        "`circuits/lib/src/merkle.nr` builds and verifies Poseidon2 Merkle trees whose",
        "depth is a compile-time generic (`<let DEPTH: u32>`). The helpers accept any",
        f"depth from 1 to `MAX_TREE_DEPTH` = {max_depth} ({1 << max_depth:,} leaves).",
        "",
        "## Cost per depth",
        "",
        "Verification walks one Poseidon2 permutation per level, so its cost is",
        "linear in the depth. Building a root hashes every internal node, so its",
        "cost is linear in the leaf count, which doubles per level. ACIR opcodes",
        "come from `nargo info`; UltraHonk gates from `bb gates`.",
        "",
        "| Depth | Leaves | Verify: ACIR opcodes | Verify: UltraHonk gates | Root: ACIR opcodes | Root: UltraHonk gates | In use by |",
        "| ----: | -----: | -------------------: | ----------------------: | -----------------: | --------------------: | --------- |",
    ]
    for r in rows:
        lines.append(
            f"| {r['depth']} | {r['leaves']:,} | {fmt(r['verify_acir'])} | {fmt(r['verify_gates'])} | "
            f"{fmt(r['root_acir'])} | {fmt(r['root_gates'])} | {IN_USE.get(r['depth'], '')} |"
        )
    lines += [
        "",
        "Root rows stop where a single root computation stops being something a",
        "circuit should do inline; above that depth callers verify inclusion proofs",
        "against a root computed off-chain (as the rank table does at depth 12).",
        "",
        "## Maximum depth and the failure mode",
        "",
        f"`MAX_TREE_DEPTH` is {max_depth}. Every depth the protocol uses is well below it",
        "(6, 9 and 12); the cap exists so a mistyped generic argument fails to compile",
        "instead of producing a circuit with millions of gates. Passing a larger",
        "depth to `verify_merkle_proof_generic`, `compute_merkle_root_generic` or",
        "`compute_merkle_proof_generic` stops at compile time with:",
        "",
        "```",
        "error: depth exceeds MAX_TREE_DEPTH",
        "```",
        "",
        "(`std::static_assert`, so it fires under `nargo check`, `nargo compile` and",
        "`nargo test` alike, before any witness is generated.)",
        "",
        "Two runtime assertions close the remaining edges:",
        "",
        "- `merkle index out of range for depth`: an index at or above 2^DEPTH is",
        "  rejected. Before this check the verifier ignored the high bits, so index",
        "  64 in a depth-6 tree verified against leaf 0's path.",
        "- `LEAVES must equal 2^DEPTH`: the root and proof builders refuse a leaf",
        "  array whose length does not match the depth, which previously produced a",
        "  partial root without complaint. The check folds to a constant and costs",
        "  no gates.",
        "",
        "## Tests",
        "",
        "`merkle.nr` covers every depth: full build-prove-verify round trips for",
        "depths 1 to 10 (first, middle and last leaf each), synthetic-path",
        f"verification for depths 11 to {max_depth}, and failing cases for an index beyond",
        "capacity, a wrong root at depth 1, a tampered sibling at the maximum depth,",
        "and a leaf count that does not match the depth. Run them with",
        "`cd circuits/lib && nargo test merkle`.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--root-max-depth", type=int, default=12, help="largest depth to measure a full root computation for")
    args = parser.parse_args()
    if shutil.which("nargo") is None:
        print("nargo is not on PATH", file=sys.stderr)
        return 1
    max_depth = max_tree_depth()
    nargo = run(["nargo", "--version"]).splitlines()[0].split("=")[-1].strip()
    bb = run(["bb", "--version"]).strip() if shutil.which("bb") else None
    rows = []
    with tempfile.TemporaryDirectory(prefix="stellpoker-merkle-depth-") as tmp:
        for depth in range(1, max_depth + 1):
            row = measure(depth, Path(tmp), depth <= args.root_max_depth)
            rows.append(row)
            print(f"  depth {depth:>2}: verify {row['verify_acir']} ACIR / {fmt(row['verify_gates'])} gates"
                  + (f", root {row['root_acir']} ACIR / {fmt(row['root_gates'])} gates" if row["root_acir"] else ""))
    DOC.write_text(render(rows, max_depth, nargo, bb))
    print(f"wrote {DOC.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
